.TH zipcracker 1 "08 April 2013" "verision 1.0" "zipcracker man page"
.SH NAME
zipcracker - zip crack tool
.SH SYNOPSIS
.B zipcracker
[--zip] 
.I ZIPFILE
[--dict] 
.I DICTFILE
.SH DESCRIPTION
Zipcracker is a fast zip cracker written in C.
.SH OPTIONS
\--zip
Specify the zip file to crack.
.SH BUGS
No known bugs.
.SH AUTHOR
.I zipcracker 
is written by Salvatore Borgia <
.I "salvo2789@gmail.com"
>
and Mauro Matteo Cascella <
.I "mauromatteo.cascella@gmail.com"
>
